name: E2E Tests Somatico

# gatilhos 
on: 
  workflow_dispatch:

jobs:
  tests: 

  # [config do so] (windows/linux/mac, chrome/firefox/edge, ...) 
    runs-on: ubuntu-latest

  #  [variaveis] (vari√°veis de ambiente, chaves de acesso a plataformas, etc.)
    env: 
      API_BASE_URL: 'http://localhost:3000'
      PORT: 4000

  # [acoes ou passos]
    steps:

    - name: Checkout do Repositorio
      uses: actions/checkout@v4

    #  [deps do projeto] (node/npm, java/maven,gradle, python/pip, ...)
  
    - name: Instalando as dependencias
      run: npm install

    - name: Iniciar servidor de aplicacao
      run: npm run server &

    - name: Executar os testes 
      run: npx cypress run
